name: stackofwax
favicon: null
layout_spectrum: 0.11606906936503947
typography_spectrum: 0.8389930312987417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8830688509624451
  lightness: 0.3279167136643082
  saturation: 0.1708105057477951
  rhythmicContrast: 0.24563773022964597
purpose: []
